#!/usr/bin/env python3
"""i-tipp-ex Layers B + C: container metadata scan.

Routes on magic bytes — never on file extension — and parses container
metadata with hand-rolled stdlib parsers. Read-only, offline.

Usage:
    python3 audit_file.py <file> [--json] [-o out] [--max-bytes N]

Programmatic use (for audit_dir.py / audit_site.py):

    from audit_file import audit_file, detect_container
    report = audit_file("/path/to/file.png", max_bytes=...)
"""

from __future__ import annotations

import io
import json
import os
import re
import shutil
import subprocess
import sys
import zipfile
import zlib
import xml.etree.ElementTree as ET

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from report import (
    DEFAULT_MAX_BYTES,
    Finding,
    Report,
    STATISTICAL_WATERMARK_NOTE,
    build_base_parser,
    emit_report,
    sniff_format,
)
import audit_text

CONTAINERS = (
    "png", "jpeg", "webp", "gif", "tiff", "svg", "pdf", "docx",
    "odt", "epub", "html", "markdown", "text", "unknown-binary",
)

# Core AI-generator markers (matched case-insensitively on decoded text).
AI_MARKERS = (
    "stable diffusion", "stablediffusion", "dall-e", "dall·e", "midjourney",
    "comfyui", "automatic1111", "novelai", "firefly", "copilot", "chatgpt",
    "gpt-3", "gpt-4", "gpt-5", "openai", "claude", "anthropic", "gemini",
    "bard", "jasper", "copy.ai", "writesonic", "leonardo.ai", "ideogram",
    "sdxl", "stable-diffusion", "ai-generated", "ai generated",
    "generated by ai", "llm", "llms.txt",
)

# Weaker markers that only count inside dedicated prompt/parameter fields.
PROMPT_FIELD_MARKERS = ("steps:", "sampler", "cfg scale", "negative prompt", "seed:")

CMS_GENERATORS = (
    "wordpress", "drupal", "joomla", "hugo", "jekyll", "wix", "squarespace",
    "shopify", "ghost", "blogger", "typo3",
)

CMS_GENERATOR_NOTE = "CMS generator tag — informational, not an AI finding"

C2PATOOL_ABSENT_NOTE = (
    "c2patool not found on PATH; install it for full claim generator / "
    "assertions / signing identity detail."
)

INCREMENTAL_EDIT_NOTE = (
    "exiftool-style incremental edits can leave recoverable metadata bytes "
    "outside the live object graph"
)

_HEAD = 8192


# ---------------------------------------------------------------------------
# Container detection (magic bytes / zip namelist — never extension)
# ---------------------------------------------------------------------------

def detect_container(source) -> str:
    """Return one of CONTAINERS for a path, bytes, or binary file object."""
    if hasattr(source, "read"):
        head = source.read(_HEAD)
        full = None
    elif isinstance(source, (bytes, bytearray)):
        head = bytes(source[:_HEAD])
        full = bytes(source)
    else:
        with open(os.fspath(source), "rb") as fh:
            head = fh.read(_HEAD)
        full = None

    def _full_bytes():
        if full is not None:
            return full
        if hasattr(source, "read"):
            source.seek(0)
            return source.read()
        with open(os.fspath(source), "rb") as fh:
            return fh.read()

    if head.startswith(b"\x89PNG\r\n\x1a\n"):
        return "png"
    if head.startswith(b"\xff\xd8\xff"):
        return "jpeg"
    if head[:4] == b"RIFF" and head[8:12] == b"WEBP":
        return "webp"
    if head.startswith(b"GIF8"):
        return "gif"
    if head[:4] in (b"II*\x00", b"MM\x00*", b"II+\x00", b"MM\x00+"):
        return "tiff"
    if head.startswith(b"%PDF"):
        return "pdf"
    if head.startswith(b"PK\x03\x04"):
        try:
            zf = zipfile.ZipFile(io.BytesIO(_full_bytes()))
            names = set(zf.namelist())
            if "mimetype" in names:
                mt = zf.read("mimetype")[:128].decode("ascii", "replace")
                if mt.startswith("application/vnd.oasis.opendocument"):
                    return "odt"
            if "word/document.xml" in names:
                return "docx"
            if "META-INF/container.xml" in names and any(
                    n.endswith(".opf") for n in names):
                return "epub"
        except (zipfile.BadZipFile, KeyError, OSError):
            pass
        return "unknown-binary"

    if sniff_format(head) == "binary":
        return "unknown-binary"

    text = head.decode("utf-8", "replace")
    stripped = text.lstrip()
    low = stripped[:1024].lower()
    if low.startswith("<?xml") and "<svg" in low or low.startswith("<svg"):
        return "svg"
    if re.match(r"^---[ \t]*\r?\n", stripped):
        return "markdown"
    if low.startswith("<!doctype html") or low.startswith("<html") \
            or "<meta" in text[:1024].lower():
        return "html"
    return "text"


# ---------------------------------------------------------------------------
# Shared field-check helper
# ---------------------------------------------------------------------------

def find_ai_markers(text: str) -> list[str]:
    low = text.lower()
    return [m for m in AI_MARKERS if m in low]


def check_metadata_value(field: str, value: str, location: str,
                         findings: list[Finding],
                         informational_otherwise: bool = True) -> None:
    """Append a finding if value carries AI markers; optionally informational."""
    markers = find_ai_markers(value)
    short = value if len(value) <= 160 else value[:157] + "..."
    if markers:
        findings.append(Finding(
            severity="medium", confidence="confirmed", category="ai-metadata",
            location=location,
            evidence=f"{field}={short}",
            note=f"AI-generator marker(s): {', '.join(markers)}",
        ))
    elif informational_otherwise and value.strip():
        findings.append(Finding(
            severity="informational", confidence="confirmed",
            category="generator-meta",
            location=location,
            evidence=f"{field}={short}",
            note="metadata field present; no AI-generator markers found",
        ))


def _xmp_scan(packet: str, location: str, findings: list[Finding]) -> None:
    """Scan an XMP packet for CreatorTool, c2pa namespace, AI markers."""
    if "c2pa:" in packet or "ns.adobe.com/c2pa" in packet:
        findings.append(Finding(
            severity="medium", confidence="confirmed", category="c2pa-manifest",
            location=location,
            evidence="XMP packet references the c2pa: namespace",
            note="C2PA metadata present in XMP",
        ))
    m = re.search(r"xmp:CreatorTool[\"'>\s]*=?[\"'>]?\s*([^<\"']+)", packet)
    if m:
        check_metadata_value("xmp:CreatorTool", m.group(1).strip(),
                             location, findings)
    markers = find_ai_markers(packet)
    if markers:
        findings.append(Finding(
            severity="medium", confidence="confirmed", category="ai-metadata",
            location=location,
            evidence="XMP packet contains AI-generator marker(s)",
            context=packet[:160],
            note=f"AI-generator marker(s): {', '.join(markers)}",
        ))


def _c2pa_finding(location: str, evidence: str) -> Finding:
    return Finding(
        severity="medium", confidence="confirmed", category="c2pa-manifest",
        location=location, evidence=evidence,
        note="content-credential manifest chunk present in container",
    )


# ---------------------------------------------------------------------------
# PNG
# ---------------------------------------------------------------------------

def _png_text_value(keyword: str, value: str, location: str,
                    findings: list[Finding]) -> None:
    kw = keyword.lower()
    if kw in ("parameters", "prompt") and any(
            m in value.lower() for m in PROMPT_FIELD_MARKERS):
        short = value if len(value) <= 200 else value[:197] + "..."
        findings.append(Finding(
            severity="medium", confidence="confirmed", category="generator-meta",
            location=location,
            evidence=f"{keyword}={short}",
            note="prompt/generation-parameter metadata typical of image "
                 "generators (e.g. AUTOMATIC1111-style PNG info)",
        ))
        return
    if kw == "xml:com.adobe.xmp":
        _xmp_scan(value, location, findings)
        return
    if kw in ("software", "comment", "parameters", "prompt", "title",
              "description", "author"):
        check_metadata_value(keyword, value, location, findings)


def parse_png(data: bytes) -> list[Finding]:
    findings: list[Finding] = []
    pos = 8  # after signature
    idx = 0
    while pos + 8 <= len(data):
        length = int.from_bytes(data[pos:pos + 4], "big")
        ctype = data[pos + 4:pos + 8]
        cdata = data[pos + 8:pos + 8 + length]
        if len(cdata) < length:
            break
        loc = f"PNG chunk {ctype.decode('latin-1', 'replace')!r} (#{idx})"
        idx += 1
        if ctype == b"caBX" or ctype.lower() == b"c2pa":
            findings.append(_c2pa_finding(loc, f"{ctype.decode('latin-1')} chunk "
                                               f"({length} bytes)"))
        elif ctype == b"tEXt":
            keyword, _, value = cdata.partition(b"\x00")
            _png_text_value(keyword.decode("latin-1", "replace"),
                            value.decode("latin-1", "replace"), loc, findings)
        elif ctype == b"zTXt":
            keyword, _, rest = cdata.partition(b"\x00")
            try:
                value = zlib.decompress(rest[1:]).decode("utf-8", "replace")
                _png_text_value(keyword.decode("latin-1", "replace"),
                                value, loc, findings)
            except (zlib.error, IndexError):
                pass
        elif ctype == b"iTXt":
            try:
                kw_end = cdata.index(b"\x00")
                keyword = cdata[:kw_end].decode("utf-8", "replace")
                rest = cdata[kw_end + 1:]
                flag, rest = rest[0], rest[2:]
                lang_end = rest.index(b"\x00")
                rest = rest[lang_end + 1:]
                tr_end = rest.index(b"\x00")
                value = rest[tr_end + 1:]
                if flag == 1:
                    value = zlib.decompress(value)
                _png_text_value(keyword, value.decode("utf-8", "replace"),
                                loc, findings)
            except (ValueError, IndexError, zlib.error):
                pass
        pos += 8 + length + 4  # skip CRC
        if ctype == b"IEND":
            break
    return findings


# ---------------------------------------------------------------------------
# Minimal TIFF / EXIF IFD0 reader (classic + BigTIFF)
# ---------------------------------------------------------------------------

def _tiff_ascii_fields(tiff: bytes, location: str,
                       findings: list[Finding]) -> None:
    if len(tiff) < 8:
        return
    bo = tiff[:2]
    if bo == b"II":
        endian = "little"
    elif bo == b"MM":
        endian = "big"
    else:
        return
    magic = int.from_bytes(tiff[2:4], endian)
    bigtiff = magic == 43
    if not bigtiff and magic != 42:
        return

    def u16(b: bytes) -> int:
        return int.from_bytes(b, endian)

    if bigtiff:
        ifd_off = int.from_bytes(tiff[8:16], endian)
        entry_size, count_len = 20, 8
    else:
        ifd_off = int.from_bytes(tiff[4:8], endian)
        entry_size, count_len = 12, 4
    if ifd_off >= len(tiff):
        return
    if bigtiff:
        n = int.from_bytes(tiff[ifd_off:ifd_off + 8], endian)
        entries_at = ifd_off + 8
    else:
        n = u16(tiff[ifd_off:ifd_off + 2])
        entries_at = ifd_off + 2

    TAG_NAMES = {0x010F: "Make", 0x0110: "Model", 0x0131: "Software",
                 0x010E: "ImageDescription", 0x02BC: "XMP"}
    for i in range(min(n, 512)):
        off = entries_at + i * entry_size
        if off + entry_size > len(tiff):
            break
        tag = u16(tiff[off:off + 2])
        typ = u16(tiff[off + 2:off + 4])
        count = int.from_bytes(tiff[off + 4:off + 4 + count_len], endian)
        inline = 8 if bigtiff else 4
        if count > 65536:
            continue
        if count <= inline:
            raw = tiff[off + 4 + count_len: off + 4 + count_len + count]
        else:
            voff = int.from_bytes(
                tiff[off + 4 + count_len: off + 4 + count_len + inline], endian)
            raw = tiff[voff:voff + count]
        name = TAG_NAMES.get(tag)
        if name is None or not raw:
            continue
        if name == "XMP":
            _xmp_scan(raw.decode("utf-8", "replace"),
                      f"{location} tag 0x02BC", findings)
            continue
        if typ not in (1, 2, 7):
            continue
        value = raw.split(b"\x00")[0].decode("utf-8", "replace").strip()
        if value:
            check_metadata_value(name, value, f"{location} {name}", findings)


# ---------------------------------------------------------------------------
# JPEG
# ---------------------------------------------------------------------------

def parse_jpeg(data: bytes) -> list[Finding]:
    findings: list[Finding] = []
    pos = 2  # after SOI
    while pos + 4 <= len(data):
        if data[pos] != 0xFF:
            pos += 1
            continue
        marker = data[pos + 1]
        if marker == 0xDA:  # SOS: image data begins
            break
        if marker in (0xD8, 0xD9) or 0xD0 <= marker <= 0xD7 or marker == 0x01:
            pos += 2
            continue
        length = int.from_bytes(data[pos + 2:pos + 4], "big")
        if length < 2:
            break
        seg = data[pos + 4:pos + 2 + length]
        loc = f"JPEG APP{marker - 0xE0}" if 0xE0 <= marker <= 0xEF else \
            f"JPEG marker 0xFF{marker:02X}"
        if marker == 0xE1:  # APP1
            if seg.startswith(b"Exif\x00\x00"):
                _tiff_ascii_fields(seg[6:], f"{loc} EXIF", findings)
            elif seg.startswith(b"http://ns.adobe.com/xap/1.0/\x00"):
                _xmp_scan(seg[29:].decode("utf-8", "replace"),
                          f"{loc} XMP", findings)
        elif marker == 0xEB:  # APP11
            if seg[:2] == b"JP":
                findings.append(_c2pa_finding(
                    loc, "APP11 JUMBF box (JP header) — C2PA manifest store"))
        elif marker == 0xFE:  # COM
            check_metadata_value("COM", seg.decode("utf-8", "replace"),
                                 "JPEG COM segment", findings)
        pos += 2 + length
    return findings


# ---------------------------------------------------------------------------
# WebP
# ---------------------------------------------------------------------------

def parse_webp(data: bytes) -> list[Finding]:
    findings: list[Finding] = []
    pos = 12
    while pos + 8 <= len(data):
        fourcc = data[pos:pos + 4]
        size = int.from_bytes(data[pos + 4:pos + 8], "little")
        payload = data[pos + 8:pos + 8 + size]
        loc = f"WebP chunk {fourcc.decode('latin-1', 'replace')!r}"
        if fourcc == b"C2PA":
            findings.append(_c2pa_finding(loc, f"C2PA chunk ({size} bytes)"))
        elif fourcc == b"XMP ":
            _xmp_scan(payload.decode("utf-8", "replace"), loc, findings)
        elif fourcc == b"EXIF":
            _tiff_ascii_fields(payload, loc, findings)
        pos += 8 + size + (size & 1)
    return findings


# ---------------------------------------------------------------------------
# GIF
# ---------------------------------------------------------------------------

def _gif_subblocks(data: bytes, pos: int) -> tuple[bytes, int]:
    out = bytearray()
    while pos < len(data):
        n = data[pos]
        pos += 1
        if n == 0:
            break
        out += data[pos:pos + n]
        pos += n
    return bytes(out), pos


def parse_gif(data: bytes) -> list[Finding]:
    findings: list[Finding] = []
    if len(data) < 13:
        return findings
    pos = 6  # header
    packed = data[10]
    pos = 13
    if packed & 0x80:  # global color table
        pos += 3 * (2 ** ((packed & 0x07) + 1))
    while pos < len(data):
        b = data[pos]
        if b == 0x3B:  # trailer
            break
        if b == 0x2C:  # image descriptor
            packed = data[pos + 9] if pos + 9 < len(data) else 0
            pos += 10
            if packed & 0x80:
                pos += 3 * (2 ** ((packed & 0x07) + 1))
            pos += 1  # LZW min code size
            _, pos = _gif_subblocks(data, pos)
            continue
        if b == 0x21 and pos + 1 < len(data):
            label = data[pos + 1]
            if label == 0xFE:  # comment extension
                payload, pos = _gif_subblocks(data, pos + 2)
                check_metadata_value(
                    "GIF comment", payload.decode("utf-8", "replace"),
                    "GIF comment extension", findings)
                continue
            if label == 0xFF:  # application extension
                app_id = data[pos + 2:pos + 13]
                payload, pos = _gif_subblocks(data, pos + 14)
                if b"XMP" in app_id:
                    _xmp_scan(payload.decode("utf-8", "replace"),
                              "GIF application extension (XMP)", findings)
                else:
                    markers = find_ai_markers(payload.decode("utf-8", "replace"))
                    if markers:
                        findings.append(Finding(
                            severity="medium", confidence="confirmed",
                            category="ai-metadata",
                            location="GIF application extension",
                            evidence=f"application {app_id.decode('latin-1', 'replace')!r} "
                                     "data contains AI-generator marker(s)",
                            note=f"AI-generator marker(s): {', '.join(markers)}",
                        ))
                continue
            pos += 2
            _, pos = _gif_subblocks(data, pos)
            continue
        pos += 1
    return findings


# ---------------------------------------------------------------------------
# SVG
# ---------------------------------------------------------------------------

def _local(tag: str) -> str:
    return tag.rsplit("}", 1)[-1].lower()


def parse_svg(text: str) -> list[Finding]:
    findings: list[Finding] = []
    try:
        root = ET.fromstring(text)
    except ET.ParseError as e:
        findings.append(Finding(
            severity="informational", confidence="informational",
            category="generator-meta", location="SVG document",
            evidence=f"SVG XML parse failed: {e}",
            note="metadata scan skipped for malformed SVG",
        ))
        return findings
    for key in root.attrib:
        ns = key.lower()
        if "inkscape" in ns or "sodipodi" in ns:
            findings.append(Finding(
                severity="informational", confidence="confirmed",
                category="generator-meta", location="SVG root attributes",
                evidence=f"namespace attribute {key}",
                note="Inkscape/sodipodi editor namespace — editor metadata, "
                     "not an AI finding",
            ))
    for elem in root.iter():
        tag = _local(elem.tag)
        for attr, val in elem.attrib.items():
            if _local(attr) == "generator":
                check_metadata_value("generator", val,
                                     f"SVG <{tag}> generator attribute",
                                     findings)
        if tag in ("metadata", "rdf", "title", "desc") and elem.text:
            markers = find_ai_markers(elem.text)
            if markers:
                findings.append(Finding(
                    severity="medium", confidence="confirmed",
                    category="ai-metadata", location=f"SVG <{tag}>",
                    evidence=elem.text.strip()[:160],
                    note=f"AI-generator marker(s): {', '.join(markers)}",
                ))
            elif tag == "metadata" and elem.text.strip():
                _xmp_scan(elem.text, "SVG <metadata>", findings)
    return findings


# ---------------------------------------------------------------------------
# PDF (byte-level scan; no full parser)
# ---------------------------------------------------------------------------

_PDF_FIELD_RE = re.compile(
    rb"/(Producer|Creator|Title|Author|CreationDate)\s*\(((?:[^()\\]|\\.)*)\)")

_PDF_ESCAPES = {b"\\n": "\n", b"\\r": "\r", b"\\t": "\t",
                b"\\(": "(", b"\\)": ")", b"\\\\": "\\"}


def _pdf_unescape(raw: bytes) -> str:
    s = raw
    for k, v in _PDF_ESCAPES.items():
        s = s.replace(k, v.encode("latin-1"))
    return s.decode("latin-1", "replace")


def _flate_stream_spans(data: bytes) -> list[tuple[int, int]]:
    """Spans of stream...endstream regions that follow a /FlateDecode filter."""
    spans = []
    for m in re.finditer(rb"\bstream\r?\n", data):
        if data[max(0, m.start() - 3):m.start()] == b"end":
            continue  # this is the 'stream' inside 'endstream'
        e = data.find(b"endstream", m.end())
        if e == -1:
            continue
        prefix = data[max(0, m.start() - 1024):m.start()]
        if b"/FlateDecode" in prefix:
            spans.append((m.start(), e + len(b"endstream")))
    return spans


def parse_pdf(data: bytes) -> list[Finding]:
    findings: list[Finding] = []
    for m in _PDF_FIELD_RE.finditer(data):
        field = m.group(1).decode()
        value = _pdf_unescape(m.group(2)).strip()
        if value:
            check_metadata_value(f"/{field}", value,
                                 f"PDF /Info /{field}", findings)

    xs = data.find(b"<?xpacket")
    if xs != -1:
        xe = data.find(b"<?xpacket end", xs)
        packet = data[xs: xe if xe != -1 else xs + 65536]
        _xmp_scan(packet.decode("utf-8", "replace"),
                  "PDF XMP metadata stream", findings)

    # Whole-file marker scan, excluding FlateDecode stream payloads.
    spans = _flate_stream_spans(data)
    excluded = bytearray(data)
    for s0, s1 in spans:
        excluded[s0:s1] = b"\x00" * (s1 - s0)
    markers = find_ai_markers(bytes(excluded).decode("latin-1", "replace"))
    already = {f.evidence for f in findings}
    if markers and not any(all(mk in ev.lower() for mk in markers)
                           for ev in already):
        findings.append(Finding(
            severity="medium", confidence="confirmed", category="ai-metadata",
            location="PDF (outside compressed streams)",
            evidence="AI-generator marker bytes present",
            note=f"AI-generator marker(s): {', '.join(markers)}; "
                 "compressed /FlateDecode stream payloads were excluded "
                 "from this scan",
        ))
    if data.count(b"%%EOF") > 1 and markers:
        findings[-1].note += ". " + INCREMENTAL_EDIT_NOTE + "."
    return findings


# ---------------------------------------------------------------------------
# OOXML (docx) / ODF (odt) / EPUB — via zipfile + ElementTree
# ---------------------------------------------------------------------------

def _xml_texts(xml_bytes: bytes, wanted: set[str]) -> list[tuple[str, str]]:
    """Return (local_tag, text) pairs for elements whose local name is wanted."""
    out = []
    try:
        root = ET.fromstring(xml_bytes)
    except ET.ParseError:
        return out
    for elem in root.iter():
        if _local(elem.tag) in wanted and elem.text and elem.text.strip():
            out.append((_local(elem.tag), elem.text.strip()))
    return out


def parse_docx(data: bytes) -> list[Finding]:
    findings: list[Finding] = []
    zf = zipfile.ZipFile(io.BytesIO(data))
    names = set(zf.namelist())

    if "docProps/core.xml" in names:
        for tag, text in _xml_texts(zf.read("docProps/core.xml"),
                                    {"creator", "lastmodifiedby"}):
            check_metadata_value(f"core.xml {tag}", text,
                                 "docProps/core.xml", findings)
    if "docProps/app.xml" in names:
        for tag, text in _xml_texts(zf.read("docProps/app.xml"),
                                    {"application", "appversion", "company"}):
            if tag == "application":
                markers = find_ai_markers(text)
                if markers:
                    findings.append(Finding(
                        severity="medium", confidence="confirmed",
                        category="ai-metadata",
                        location="docProps/app.xml",
                        evidence=f"Application={text}",
                        note=f"AI-generator marker(s): {', '.join(markers)}",
                    ))
                else:
                    findings.append(Finding(
                        severity="informational", confidence="confirmed",
                        category="generator-meta",
                        location="docProps/app.xml",
                        evidence=f"Application={text}",
                        note="authoring application; no AI-generator markers",
                    ))
            else:
                check_metadata_value(f"app.xml {tag}", text,
                                     "docProps/app.xml", findings)
    if "docProps/custom.xml" in names:
        try:
            root = ET.fromstring(zf.read("docProps/custom.xml"))
            for prop in root:
                name = prop.attrib.get("name", "?")
                for child in prop:
                    if child.text:
                        check_metadata_value(f"custom property {name!r}",
                                             child.text.strip(),
                                             "docProps/custom.xml", findings)
        except ET.ParseError:
            pass
    for name in sorted(names):
        if name.startswith("customXml/") and name.endswith(".xml"):
            for tag, text in _xml_texts(zf.read(name),
                                        {"creator", "generator", "tool"}):
                check_metadata_value(f"{name} {tag}", text, name, findings)
    return findings


def parse_odt(data: bytes) -> list[Finding]:
    findings: list[Finding] = []
    zf = zipfile.ZipFile(io.BytesIO(data))
    if "meta.xml" not in zf.namelist():
        return findings
    wanted = {"generator", "initial-creator", "creator", "creation-date"}
    for tag, text in _xml_texts(zf.read("meta.xml"), wanted):
        markers = find_ai_markers(text)
        if markers:
            findings.append(Finding(
                severity="medium", confidence="confirmed",
                category="ai-metadata", location=f"meta.xml {tag}",
                evidence=f"{tag}={text}",
                note=f"AI-generator marker(s): {', '.join(markers)}",
            ))
        else:
            findings.append(Finding(
                severity="informational", confidence="confirmed",
                category="generator-meta", location=f"meta.xml {tag}",
                evidence=f"{tag}={text}",
                note="ODF metadata field; no AI-generator markers",
            ))
    return findings


_JSONLD_RE = re.compile(
    r"<script[^>]*type=[\"']application/ld\+json[\"'][^>]*>(.*?)</script>",
    re.I | re.S)


def _scan_jsonld_blocks(text: str, location: str,
                        findings: list[Finding]) -> None:
    for m in _JSONLD_RE.finditer(text):
        markers = find_ai_markers(m.group(1))
        if markers:
            findings.append(Finding(
                severity="medium", confidence="confirmed",
                category="ai-metadata", location=location,
                evidence="JSON-LD block contains AI-generator marker(s)",
                context=m.group(1).strip()[:160],
                note=f"AI-generator marker(s): {', '.join(markers)}",
            ))


def parse_epub(data: bytes) -> list[Finding]:
    findings: list[Finding] = []
    zf = zipfile.ZipFile(io.BytesIO(data))
    for name in sorted(zf.namelist()):
        low = name.lower()
        if low.endswith(".opf"):
            for tag, text in _xml_texts(zf.read(name),
                                        {"creator", "generator", "meta"}):
                check_metadata_value(f"{name} {tag}", text, name, findings)
        elif low.endswith((".xhtml", ".html", ".htm")):
            text = zf.read(name).decode("utf-8", "replace")
            for m in re.finditer(r"<meta\b[^>]*>", text, re.I):
                attrs = dict(re.findall(
                    r"([\w:-]+)\s*=\s*[\"']([^\"']*)[\"']", m.group()))
                if attrs.get("name", "").lower() == "generator":
                    check_metadata_value("meta generator",
                                         attrs.get("content", ""),
                                         f"{name} <meta generator>", findings)
            _scan_jsonld_blocks(text, f"{name} JSON-LD", findings)
    return findings


# ---------------------------------------------------------------------------
# HTML
# ---------------------------------------------------------------------------

def parse_html(text: str) -> list[Finding]:
    findings: list[Finding] = []
    for m in re.finditer(r"<meta\b[^>]*>", text, re.I):
        attrs = {k.lower(): v for k, v in re.findall(
            r"([\w:-]+)\s*=\s*[\"']([^\"']*)[\"']", m.group())}
        if attrs.get("name", "").lower() != "generator":
            continue
        content = attrs.get("content", "")
        markers = find_ai_markers(content)
        if markers:
            findings.append(Finding(
                severity="medium", confidence="confirmed",
                category="ai-metadata", location="<meta name=\"generator\">",
                evidence=f"generator={content}",
                note=f"AI-generator marker(s): {', '.join(markers)}",
            ))
        elif any(cms in content.lower() for cms in CMS_GENERATORS):
            findings.append(Finding(
                severity="informational", confidence="confirmed",
                category="generator-meta", location="<meta name=\"generator\">",
                evidence=f"generator={content}", note=CMS_GENERATOR_NOTE,
            ))
        elif content.strip():
            findings.append(Finding(
                severity="informational", confidence="confirmed",
                category="generator-meta", location="<meta name=\"generator\">",
                evidence=f"generator={content}",
                note="generator tag present; not a known CMS, no AI markers",
            ))
    for m in re.finditer(r"\s(data-ai[\w-]*)\s*=\s*[\"']([^\"']*)[\"']",
                         text, re.I):
        findings.append(Finding(
            severity="medium", confidence="confirmed", category="ai-metadata",
            location=f"attribute {m.group(1)}",
            evidence=f"{m.group(1)}={m.group(2)}",
            note="data-ai* attribute present in markup",
        ))
    _scan_jsonld_blocks(text, "JSON-LD script block", findings)
    return findings


# ---------------------------------------------------------------------------
# Markdown (YAML frontmatter only, line-based — no yaml lib)
# ---------------------------------------------------------------------------

_FRONTMATTER_KEY_RE = re.compile(
    r"^(generator|model|ai[-_].*|claude.*|gpt.*|llm.*)$", re.I)


def parse_markdown(text: str) -> list[Finding]:
    findings: list[Finding] = []
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return findings
    end = None
    for i in range(1, len(lines)):
        if lines[i].strip() == "---":
            end = i
            break
    if end is None:
        return findings
    for i in range(1, end):
        m = re.match(r"^([A-Za-z0-9_.-]+)\s*:\s*(.*)$", lines[i])
        if not m:
            continue
        key, value = m.group(1), m.group(2).strip().strip("\"'")
        markers = find_ai_markers(value)
        if _FRONTMATTER_KEY_RE.match(key) or markers:
            findings.append(Finding(
                severity="medium", confidence="confirmed",
                category="ai-metadata",
                location=f"frontmatter line {i + 1}",
                evidence=f"{key}: {value}",
                note=("AI-related frontmatter key"
                      if _FRONTMATTER_KEY_RE.match(key) else
                      f"AI-generator marker(s) in value: {', '.join(markers)}"),
            ))
    return findings


# ---------------------------------------------------------------------------
# Layer C: c2patool enrichment (optional, only when on PATH)
# ---------------------------------------------------------------------------

def enrich_c2pa(path: str, report: Report) -> None:
    """Cross-check c2pa-manifest findings with c2patool when available.

    Never treats c2patool errors as presence: nonzero exit or "No claim
    found" / "No JUMBF data found" output means the manifest is ABSENT;
    chunk-scan findings are then removed and the discrepancy noted.
    """
    c2pa_findings = [f for f in report.findings if f.category == "c2pa-manifest"]
    if not c2pa_findings:
        return
    tool = shutil.which("c2patool")
    if not tool:
        report.add_note(C2PATOOL_ABSENT_NOTE)
        return
    try:
        proc = subprocess.run([tool, path], capture_output=True, text=True,
                              timeout=30)
    except (OSError, subprocess.TimeoutExpired) as e:
        report.add_note(f"c2patool could not be run ({e}); manifest "
                        "findings are chunk-scan only and unverified.")
        return
    combined = (proc.stdout or "") + "\n" + (proc.stderr or "")
    if proc.returncode != 0 or "No claim found" in combined \
            or "No JUMBF data found" in combined:
        report.findings = [f for f in report.findings
                           if f.category != "c2pa-manifest"]
        report.add_note(
            "chunk scan indicated C2PA data, but c2patool reported no "
            "claim; c2pa-manifest findings removed as a likely stale or "
            "malformed chunk.")
        return
    try:
        manifest = json.loads(proc.stdout)
    except (json.JSONDecodeError, TypeError):
        report.add_note("c2patool output was not parseable JSON; manifest "
                        "findings are chunk-scan only.")
        return
    manifests = manifest.get("manifests", {})
    active = manifests.get(manifest.get("active_manifest"), {}) \
        if isinstance(manifests, dict) else {}
    gen = active.get("claim_generator", "")
    assertions = [a.get("label", "?")
                  for a in active.get("assertions", [])
                  if isinstance(a, dict)]
    sig = active.get("signature_info", {})
    signer = sig.get("issuer", "") or sig.get("common_name", "")
    for f in c2pa_findings:
        detail = []
        if gen:
            detail.append(f"claim_generator={gen}")
        if assertions:
            detail.append(f"assertions: {', '.join(assertions)}")
        if signer:
            detail.append(f"signed by: {signer}")
        if detail:
            f.note += ". c2patool: " + "; ".join(detail)


# ---------------------------------------------------------------------------
# Core audit entry point
# ---------------------------------------------------------------------------

_TEXTUAL = {"text", "markdown", "html", "svg"}


def audit_file(path: str, max_bytes: int = DEFAULT_MAX_BYTES) -> Report:
    """Audit one file; never modifies it. Returns a Report."""
    report = Report(target=path)
    with open(path, "rb") as fh:
        raw = fh.read(max(0, max_bytes) + 1)
    if len(raw) > max_bytes:
        raw = raw[:max_bytes]
        report.add_note(f"Input truncated at {max_bytes} bytes "
                        "(--max-bytes); findings cover only that prefix.")

    container = detect_container(raw)
    findings: list[Finding] = []
    text_scanned = False

    if container == "png":
        findings = parse_png(raw)
    elif container == "jpeg":
        findings = parse_jpeg(raw)
    elif container == "webp":
        findings = parse_webp(raw)
    elif container == "gif":
        findings = parse_gif(raw)
    elif container == "tiff":
        _tiff_ascii_fields(raw, "TIFF IFD0", findings)
    elif container == "pdf":
        findings = parse_pdf(raw)
    elif container == "docx":
        try:
            findings = parse_docx(raw)
        except (zipfile.BadZipFile, OSError) as e:
            report.add_note(f"could not open DOCX zip: {e}")
    elif container == "odt":
        try:
            findings = parse_odt(raw)
        except (zipfile.BadZipFile, OSError) as e:
            report.add_note(f"could not open ODT zip: {e}")
    elif container == "epub":
        try:
            findings = parse_epub(raw)
        except (zipfile.BadZipFile, OSError) as e:
            report.add_note(f"could not open EPUB zip: {e}")
    elif container in _TEXTUAL:
        text = raw.decode("utf-8", "replace")
        if container == "svg":
            findings = parse_svg(text)
        elif container == "html":
            findings = parse_html(text)
        elif container == "markdown":
            findings = parse_markdown(text)
        findings.extend(audit_text.scan_text(text))
        text_scanned = True
    else:  # unknown-binary
        report.add_note(
            "unrecognized binary format, no metadata scan performed")

    for f in findings:
        report.add_finding(f)

    if any(f.category == "c2pa-manifest" for f in report.findings):
        enrich_c2pa(path, report)
    if text_scanned:
        report.add_note(STATISTICAL_WATERMARK_NOTE)
    return report


def main(argv=None) -> int:
    parser = build_base_parser(
        description="i-tipp-ex Layers B+C: container metadata audit "
                    "(C2PA, EXIF/XMP, generator markers). Read-only, offline."
    )
    parser.add_argument("file", help="file to audit (routed by magic bytes)")
    args = parser.parse_args(argv)
    report = audit_file(args.file, max_bytes=args.max_bytes)
    emit_report(report, args)
    return 0


if __name__ == "__main__":
    sys.exit(main())
